### ISSUE TITLE
`mkNewFact` is not compatible with GHC HEAD

### ISSUE THREAD

**Issue by plaidfinch** [yav/type-nat-solver#4]
In attempting to compile the plugin for GHC HEAD, I get only one compile error, for the function `mkNewFact`:

``` Haskell
mkNewFact :: CtLoc -> Bool -> (Type,Type) -> CtEvidence
mkNewFact newLoc withEv (t1,t2)
  | withEv = CtGiven { ctev_pred = newPred
                     , ctev_evtm = evBy (t1,t2)
                     , ctev_loc  = newLoc
                     }
  | otherwise = CtDerived { ctev_pred = newPred
                          , ctev_loc  = newLoc
                          }
  where
  newPred = mkEqPred t1 t2
```

The problem is that the `ctev_evtm` field of the `CtGiven` constructor on the `CtEvidence` type has changed; it is now `ctev_evar`, of type `EvVar`, while it used to be of type `EvTerm`. I believe this is due to changes in the constraint solver architecture for GHC 8.0—@goldfirere would know more about this, I'm pretty sure.

In any case, we need to find a way to shoe-horn the manufactured evidence into an `EvVar` now. I'm not sure which bits of the `EvVar` infrastructure should be used to replicate the previous behavior; any ideas?

**Comment by adamgundry** [comment]
The `TcPluginM` module of the GHC API now exports `newWanted`/`newGiven`/`newDerived` functions that should help here. You might also be interested in [ghc-tcplugins-extra](https://github.com/clash-lang/ghc-tcplugins-extra), which is intended to contain common functionality for plugins and to paper over the differences between different versions of the GHC API.

**Comment by plaidfinch** [comment]
Works perfectly; thanks @adamgundry. I just submitted a pull request with this patch.
